import React from "react";
import Head from "next/head";
import Link from "next/link";

import { HomeIcon } from "@heroicons/react/24/solid";

import ModalProvider from "@context/modal/modalProvider";
import PopupProvider from "@context/popup/popupProvider";
import Popup from "../popup/Popup";

export default function Layout({ children, ...props }) {
  const { title } = props;

  return (
    <>
      <Head>
        <title>Smart Light {title ?? title}</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>

      <div className='max-w-sm min-h-screen mx-auto bg-zinc-900 text-white pb-16'>
        <ModalProvider>
          <PopupProvider>
            <main>{children}</main>
            <div
              className='fixed w-full h-16 bottom-0 left-0 z-50 text-white'
              style={{
                background: "linear-gradient(to bottom, rgb(42 42 45) 0%, rgb(39 39 42)  100%)",
                borderRadius: "8px 8px 0 0",
              }}>
              <div className='flex flex-row flex-nowrap flex-auto items-center justify-between mx-auto h-full'>
                <div className='mx-auto'>
                  <Link href='/'>
                    <div className='mx-auto cursor-pointer'>
                      <div className='flex flex-row flex-nowrap'>
                        <div className='mr-6'>
                          <HomeIcon className='w-6 h-4 text-inherit' />
                        </div>
                        <p className='text-sm'>Dom</p>
                      </div>
                    </div>
                  </Link>
                </div>
              </div>
            </div>
            <Popup />
          </PopupProvider>
        </ModalProvider>

        {/* <footer className='p-8'>
                    Hi there.
                </footer> */}
      </div>
    </>
  );
}
