import React from "react";
import Head from "next/head";

export default function Layout({ children, ...props }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='max-w-sm min-h-screen mx-auto bg-zinc-900 text-white'>
        <main>{children}</main>

        {/* <footer className='p-8'>
                    Hi there.
                </footer> */}
      </div>
    </>
  );
}
